baseurl = "https://likewind.netlify.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Likewind"
theme = "dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "#AFEEEE"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Xu Jintao"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "Like wind"
  
  email = "xujintao_workspace@163.com"
  github = "https://github.com/XuJinTao1996"
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
